extends:
  - plugin:@lichtblick/base
  - plugin:@lichtblick/jest

env:
  node: true

ignorePatterns:
  - dist
  - examples
  - template

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: ./tsconfig.json